all:
	perl main.pl
	perl ranking.pl SM3DW 1000
	perl ranking.pl SM3DW 100
	node main.mjs
	node get-json.mjs
	node clear-check.mjs

temp:
	perl ranking.pl NSMBU-Castle 1000

fetch:
	node get-jsons.mjs
